### ISSUE TITLE
Come up with database schema

### ISSUE THREAD

**Issue by mihaivavram** [mihaivavram/work-life-balance-nudger#2]
Include all tables, columns, and how they all relate

**Comment by danvolchek** [comment]
It's a little early to think about exact implementation details. We'll push this off until later.

**Comment by danvolchek** [comment]
Please see comments on e3c8e7a09275b0ae45503de3d15e10aa7d92c6bd for changes that need to be made to the schema.

**Comment by mihaivavram** [comment]
Update: We should save the schemas somewhere for future reference, but for now, we should only keep the Nudges table and rename it to something along the lines of NudgeAchievements.

Someone should look at the schema and ensure the new table is properly created and persisted to the database.

**Comment by mihaivavram** [comment]
Fixed and pushed to master. Closing!
