### ISSUE TITLE
Come up with nudging articles we can link to

### ISSUE THREAD

**Issue by mihaivavram** [mihaivavram/work-life-balance-nudger#27]
The categories we are first starting out with are Play, Sleep, and Take a Break.

We can find articles that describe:

1) The benefits of doing such actions
2) How one would do these things if they are a beginner, intermediate, or advanced (ideally an article that covers things from all perspectives is the best but I know they are hard to find so we can find a couple here)

Report back with the articles on this task as comment(s).

**Comment by mihaivavram** [comment]
The categories we are looking for are:

- Health:
    - Sleep
    - Exercise
- Happiness:
    - Social Interaction
    - Play
- Productivity:
    - Take a break

**Comment by mihaivavram** [comment]
Here's what I've found

- Health:
	- Sleep:
		- How-to: https://www.helpguide.org/articles/sleep/getting-better-sleep.htm/
		- Why: https://www.webmd.com/sleep-disorders/benefits-sleep-more#1
	- Exercise:
		- How-to: https://www.nytimes.com/guides/well/how-to-start-running
		- Why: https://www.verywellfit.com/reasons-to-start-running-4022450		
- Happiness:
	- Social Interaction:
		-How-to: https://www.wikihow.com/Interact-With-People
		-Why: https://www.nytimes.com/2017/06/12/well/live/having-friends-is-good-for-you.html
	- Play:
		-How-to: https://www.successconsciousness.com/blog/happiness-fun/take-time-to-do-things-you-enjoy-doing/
		-Why: https://www.helpguide.org/articles/mental-health/benefits-of-play-for-adults.htm/
- Productivity:
	- Take a break:
		-How-to: https://betterhumans.coach.me/the-practical-guide-to-taking-intentional-breaks-at-work-d98ca3a2f4e
		-Why: https://www.psychologytoday.com/us/blog/changepower/201704/how-do-work-breaks-help-your-brain-5-surprising-answers

**Comment by danvolchek** [comment]
The links you posted are great, Mihai. The only one I'm not sure about is the Social Interaction how to - but we can discuss this later. I've included links that I've found for categories that I thought were missing or could be added upon from your list.

- Health:
    - Sleep:
        - Why: https://www.healthline.com/health/science-sleep-why-you-need-7-8-hours-night
    - Exercise:
        - Why: https://www.verywellfit.com/top-reasons-to-lift-weights-1231112
        - How: https://thefitness.wiki/routines/r-fitness-basic-beginner-routine/
- Happiness:
    - Social Interaction:
        - How: https://www.nytimes.com/2018/10/24/smarter-living/the-edit-how-to-make-friends.html

**Comment by danvolchek** [comment]
See #43 and most recently #47, this task is done.
