### ISSUE TITLE
Come up with nudging behavior

### ISSUE THREAD

**Issue by mihaivavram** [mihaivavram/work-life-balance-nudger#4]
- Think of categories for the calendar that incorporate nudging (e.g. sleep, work, exercise) and other categories for improving productivity, health, and happiness

- Think of mechanism of how the nudging would work for each category, and in what instances the nudging would occur

- Think of how to display the nudges (e.g. list, continuous fashion like calendar reminders, etc...)

**Comment by danvolchek** [comment]
We'll split this up into smaller issues.

**Comment by danvolchek** [comment]
See #5 and #6.
