### ISSUE TITLE
Come up with nudging categories

### ISSUE THREAD

**Issue by danvolchek** [mihaivavram/work-life-balance-nudger#6]
Overall, we want users to be happy, healthy, and productive in their work life.

We should come up with specific things that can be nudged (i.e. sleep, etc).

**Comment by mihaivavram** [comment]
# Here is my take on the nudging. We can have nudging heuristics for the following:

## Health: 
- Sleep 
- Exercise
- Eating Healthy
- Meditation
- Communication (no isolation)

## Productivity: 
- Avoiding extreme working patterns
- Pomodoro Approach (work then take a break)
- Deep Focused Work (little context switching, ideally one task at once, also no distractions from phone or social media)
- Meditation
- Taking a break (go for a quick walk, chat, meditate)

## Happiness: 
- General Play
- Talking to loved ones (family/best friends)
- Meditation
- Ask activities that makes user very happy then recommend those activities from time to time

**Comment by danvolchek** [comment]
I like your list Mihai! You covered a lot of things so I won't repeat them. Here's what I came up with:

## Health
 - Suggest regular times to go grocery shopping
 - Suggest doctors visit if social events cancelled (somehow determine sadness/depression?)
 - Suggest getting flu shots before winter

## Productivity
 - Suggest times to do laundry/other time consuming household chores

## Happiness:
 - To expand upon talking to loved ones, could be make a phone call if you haven't talked to parents/etc in a while
 - Suggest social activities during free time

**Comment by danvolchek** [comment]
# Here is my take on the nudging. We can have nudging heuristics for the following:

## Health: 
- Sleep 
  - Yes, ask to track sleep.
- Exercise
  - Yes.
- Eating Healthy
  - No, people don't track food in their calender.
- Meditation
  - Yes.
- Communication (no isolation)
  - Probably too hard to figure out. Make a tip.
- Avoid sedentary sitting in one place for a long time
  - Probably too hard to figure out. Make a tip.
## Productivity: 
- Performing activities which involve "Work".
  - Yes.
- Avoiding extreme working patterns
  - Yes. Combine with the category of breaks - medition, walks, etc.
- Pomodoro Approach (work then take a break)
  - Yes, same as previous.
- Deep Focused Work (little context switching, ideally one task at once, also no distractions from the phone or social media)
  - No, context switching is hard to figure out. Make a tip.
- Meditation
 - Yes.
- Taking a break (go for a quick walk, chat, meditate)
  - Yes.

## Happiness: 
- General Play
  - Yes, if people tell us the category.
- Talking to loved ones (family/best friends)
  - Yes, given information from users.
- Meditation
  - Yes.
- Short vacation every once in a while
  - Too ambitious. Make a tip.
- Gratitude
  - Too hard. Make a tip.
- Ask activities that make the user very happy then recommend those activities from time to time
  - Make a tip. For now, just tell them to do something they enjoy. Make a tip.
