### ISSUE TITLE
Come up with how the website should look like

### ISSUE THREAD

**Issue by danvolchek** [mihaivavram/work-life-balance-nudger#7]
Overall, what should the website look like? How are nudges displayed?

**Comment by zchen138** [comment]
The primary view for the nudges should be organized chronologically with each day with nudges being characterized by a bubble.

When the bubble is clicked that day is expanded and all of its nudges for that day are displayed.

Currently we've decided that we should give a list of time periods that are free for that day. The user can click on a free time slot to chose a nudge for that time slot. Also we will prioritize nudges when the users sign up so we can put perhaps a star next to the most important nudge. 

We should also have another view where we keep track of how many nudges that the user has scheduled to give them encouragement. Perhaps we can also show how their nudges decreases with time which shows that they're actively improving themselves without a push from us.
